// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmChange();

float x;
float y;
float z;
bool alarm;

void initProperties(){

  ArduinoCloud.addProperty(x, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(z, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarm, READWRITE, ON_CHANGE, onAlarmChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
